apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: products-api
spec:
  sources:
    - name: public-api
      action: allow
    - name: public-api
      action: allow
      peer: dc1
  destination:
    name: products-api