global:
  image: 'im2nguyenhashi/consul:hashidays'
  imageK8S: 'im2nguyenhashi/consul-k8s-control-plane-dev:hashidays'
  datacenter: dc2
  peering:
    enabled: true
  tls:
    enabled: true # mandatory for cluster peering
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    defaultEnabled: true
dns:
  enabled: true
  enableRedirection: true
server:
  enabled: true
  replicas: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }
connectInject:
  enabled: true
meshGateway:
  enabled: true # mandatory for k8s cluster peering
  replicas: 1
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
