global:
  # image: "hashicorp/consul:1.15.2"
  # imageK8S: "hashicorp/consul-k8s-control-plane:1.1.1"
  # image: 'im2nguyenhashi/consul:hashidays'
  image: 'im2nguyenhashi/consul-enterprise:hashidays'
  imageK8S: 'im2nguyenhashi/consul-k8s-control-plane-dev:hashidays'
  datacenter: dc1
  # include enterprise license
  enterpriseLicense:
    secretName: 'consul-ent-license'
    secretKey: 'key'
  peering:
    enabled: true
  tls:
    enabled: true # mandatory for cluster peering
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    defaultEnabled: true
  apiGateway:
      enabled: true
      image: hashicorp/consul-api-gateway:0.5.4
      managedGatewayClass:
        # Defines the type of service created for gateways (e.g. LoadBalancer, ClusterIP, NodePort)
        # NodePort is primarily used for local deployments.
        serviceType: LoadBalancer
  cloud:
    enabled: true
    resourceId:
      secretName: "consul-hcp-resource-id"
      secretKey: "resource-id"
    clientId:
      secretName: "consul-hcp-client-id"
      secretKey: "client-id"
    clientSecret:
      secretName: "consul-hcp-client-secret"
      secretKey: "client-secret"
dns:
  enabled: true
  enableRedirection: true
server:
  enabled: true
  replicas: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }
connectInject:
  enabled: true
meshGateway:
  enabled: true # mandatory for k8s cluster peering
  replicas: 1
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
