global:
  image: 'hashicorp/consul:1.16.0-rc1'
  imageK8S: 'hashicorp/consul-k8s-control-plane:1.2.0-rc1'
  datacenter: dc1
  peering:
    enabled: true
  tls:
    enabled: true # mandatory for cluster peering
    enableAutoEncrypt: true
    verify: true
  acls:
    manageSystemACLs: true
  metrics:
    enabled: true
    defaultEnabled: true
  # cloud:
  #   enabled: true
  #   resourceId:
  #     secretName: "consul-hcp-resource-id"
  #     secretKey: "resource-id"
  #   clientId:
  #     secretName: "consul-hcp-client-id"
  #     secretKey: "client-id"
  #   clientSecret:
  #     secretName: "consul-hcp-client-secret"
  #     secretKey: "client-secret"
dns:
  enabled: true
  enableRedirection: true
server:
  enabled: true
  replicas: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }
connectInject:
  enabled: true
meshGateway:
  enabled: true # mandatory for k8s cluster peering
  replicas: 1
ui:
  enabled: true
  service:
    enabled: true
    type: LoadBalancer
